version: '3.3'

services:
  redis:
    image: redis:alpine
  
  api:
    build: ./event_generator/
    container_name: event_generator
    env_file:
      - .env
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - webhook
  
  webhook:
    build: ./webhook/
    env_file:
      - .env
    depends_on:
      - redis
